//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace eLearnWeb.VerifyEmail {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="VerifyEmailSoap", Namespace="http://tempuri.org/")]
    public partial class VerifyEmail : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SendVerificationOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendVerification1OperationCompleted;
        
        private System.Threading.SendOrPostCallback VerifyCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsUserVerifiedOperationCompleted;
        
        private System.Threading.SendOrPostCallback RegisterOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetVerifiedUsersOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public VerifyEmail() {
            this.Url = global::eLearnWeb.Properties.Settings.Default.eLearnWeb_VerifyEmail_VerifyEmail;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SendVerificationCompletedEventHandler SendVerificationCompleted;
        
        /// <remarks/>
        public event SendVerification1CompletedEventHandler SendVerification1Completed;
        
        /// <remarks/>
        public event VerifyCodeCompletedEventHandler VerifyCodeCompleted;
        
        /// <remarks/>
        public event IsUserVerifiedCompletedEventHandler IsUserVerifiedCompleted;
        
        /// <remarks/>
        public event RegisterCompletedEventHandler RegisterCompleted;
        
        /// <remarks/>
        public event GetVerifiedUsersCompletedEventHandler GetVerifiedUsersCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RegularVerify", RequestElementName="RegularVerify", RequestNamespace="http://tempuri.org/", ResponseElementName="RegularVerifyResponse", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("RegularVerifyResult")]
        public bool SendVerification(string subscriber, string email) {
            object[] results = this.Invoke("SendVerification", new object[] {
                        subscriber,
                        email});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SendVerificationAsync(string subscriber, string email) {
            this.SendVerificationAsync(subscriber, email, null);
        }
        
        /// <remarks/>
        public void SendVerificationAsync(string subscriber, string email, object userState) {
            if ((this.SendVerificationOperationCompleted == null)) {
                this.SendVerificationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendVerificationOperationCompleted);
            }
            this.InvokeAsync("SendVerification", new object[] {
                        subscriber,
                        email}, this.SendVerificationOperationCompleted, userState);
        }
        
        private void OnSendVerificationOperationCompleted(object arg) {
            if ((this.SendVerificationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendVerificationCompleted(this, new SendVerificationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute(MessageName="SendVerification1")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CustomMessageVerify", RequestElementName="CustomMessageVerify", RequestNamespace="http://tempuri.org/", ResponseElementName="CustomMessageVerifyResponse", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("CustomMessageVerifyResult")]
        public bool SendVerification(string subscriber, string email, string message) {
            object[] results = this.Invoke("SendVerification1", new object[] {
                        subscriber,
                        email,
                        message});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SendVerification1Async(string subscriber, string email, string message) {
            this.SendVerification1Async(subscriber, email, message, null);
        }
        
        /// <remarks/>
        public void SendVerification1Async(string subscriber, string email, string message, object userState) {
            if ((this.SendVerification1OperationCompleted == null)) {
                this.SendVerification1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendVerification1OperationCompleted);
            }
            this.InvokeAsync("SendVerification1", new object[] {
                        subscriber,
                        email,
                        message}, this.SendVerification1OperationCompleted, userState);
        }
        
        private void OnSendVerification1OperationCompleted(object arg) {
            if ((this.SendVerification1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendVerification1Completed(this, new SendVerification1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VerifyCode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool VerifyCode(string subscriber, string email, string code) {
            object[] results = this.Invoke("VerifyCode", new object[] {
                        subscriber,
                        email,
                        code});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void VerifyCodeAsync(string subscriber, string email, string code) {
            this.VerifyCodeAsync(subscriber, email, code, null);
        }
        
        /// <remarks/>
        public void VerifyCodeAsync(string subscriber, string email, string code, object userState) {
            if ((this.VerifyCodeOperationCompleted == null)) {
                this.VerifyCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVerifyCodeOperationCompleted);
            }
            this.InvokeAsync("VerifyCode", new object[] {
                        subscriber,
                        email,
                        code}, this.VerifyCodeOperationCompleted, userState);
        }
        
        private void OnVerifyCodeOperationCompleted(object arg) {
            if ((this.VerifyCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VerifyCodeCompleted(this, new VerifyCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IsUserVerified", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool IsUserVerified(string subscriber, string email) {
            object[] results = this.Invoke("IsUserVerified", new object[] {
                        subscriber,
                        email});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IsUserVerifiedAsync(string subscriber, string email) {
            this.IsUserVerifiedAsync(subscriber, email, null);
        }
        
        /// <remarks/>
        public void IsUserVerifiedAsync(string subscriber, string email, object userState) {
            if ((this.IsUserVerifiedOperationCompleted == null)) {
                this.IsUserVerifiedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsUserVerifiedOperationCompleted);
            }
            this.InvokeAsync("IsUserVerified", new object[] {
                        subscriber,
                        email}, this.IsUserVerifiedOperationCompleted, userState);
        }
        
        private void OnIsUserVerifiedOperationCompleted(object arg) {
            if ((this.IsUserVerifiedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsUserVerifiedCompleted(this, new IsUserVerifiedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Register", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Register(string subscriber) {
            object[] results = this.Invoke("Register", new object[] {
                        subscriber});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void RegisterAsync(string subscriber) {
            this.RegisterAsync(subscriber, null);
        }
        
        /// <remarks/>
        public void RegisterAsync(string subscriber, object userState) {
            if ((this.RegisterOperationCompleted == null)) {
                this.RegisterOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegisterOperationCompleted);
            }
            this.InvokeAsync("Register", new object[] {
                        subscriber}, this.RegisterOperationCompleted, userState);
        }
        
        private void OnRegisterOperationCompleted(object arg) {
            if ((this.RegisterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegisterCompleted(this, new RegisterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetVerifiedUsers", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetVerifiedUsers(string subscriber) {
            object[] results = this.Invoke("GetVerifiedUsers", new object[] {
                        subscriber});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetVerifiedUsersAsync(string subscriber) {
            this.GetVerifiedUsersAsync(subscriber, null);
        }
        
        /// <remarks/>
        public void GetVerifiedUsersAsync(string subscriber, object userState) {
            if ((this.GetVerifiedUsersOperationCompleted == null)) {
                this.GetVerifiedUsersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetVerifiedUsersOperationCompleted);
            }
            this.InvokeAsync("GetVerifiedUsers", new object[] {
                        subscriber}, this.GetVerifiedUsersOperationCompleted, userState);
        }
        
        private void OnGetVerifiedUsersOperationCompleted(object arg) {
            if ((this.GetVerifiedUsersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetVerifiedUsersCompleted(this, new GetVerifiedUsersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void SendVerificationCompletedEventHandler(object sender, SendVerificationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendVerificationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendVerificationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void SendVerification1CompletedEventHandler(object sender, SendVerification1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendVerification1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendVerification1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void VerifyCodeCompletedEventHandler(object sender, VerifyCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VerifyCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VerifyCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void IsUserVerifiedCompletedEventHandler(object sender, IsUserVerifiedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsUserVerifiedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsUserVerifiedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void RegisterCompletedEventHandler(object sender, RegisterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RegisterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RegisterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetVerifiedUsersCompletedEventHandler(object sender, GetVerifiedUsersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetVerifiedUsersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetVerifiedUsersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591